// <auto-generated />
using System;
using Main.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Infrastructure.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Main.Domian.Entities.test_table", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()")
                        .HasComment("Khóa chính của bảng, tự động tạo khi thêm mới");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("ngay_chinh_sua")
                        .HasColumnType("datetime2")
                        .HasComment("Thời gian chỉnh sửa bản khi, được ghi nhận khi thêm mới hoặc mỗi lần cập nhật");

                    b.Property<DateTime?>("ngay_tao")
                        .HasColumnType("datetime2")
                        .HasComment("Thời gian tạo bản khi, được ghi nhận khi thêm mới");

                    b.Property<string>("nguoi_chinh_sua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Thông tin tài khoản người chỉnh sửa bản ghi, được ghi nhận khi thêm mới hoặc mỗi lần cập nhật");

                    b.Property<string>("nguoi_tao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Thông tin tài khoản người tạo bản khi, được ghi nhận khi thêm mới");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("test_table", "main");
                });
#pragma warning restore 612, 618
        }
    }
}
